cmake_minimum_required(VERSION 3.8)
project(project_interfaces)

find_package(ament_cmake REQUIRED)
find_package(std_msgs REQUIRED)
find_package(rosidl_default_generators REQUIRED)

rosidl_generate_interfaces(${PROJECT_NAME}
  "msg/TrajectoryPoint.msg"
  "msg/Trajectory.msg"
  "msg/TrafficLight.msg"
  DEPENDENCIES std_msgs
)

ament_package()
